Document: mbsebbs
Title: Debian mbsebbs Manual
Author: <insert document author here>
Abstract: This manual describes what mbsebbs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mbsebbs/mbsebbs.sgml.gz

Format: postscript
Files: /usr/share/doc/mbsebbs/mbsebbs.ps.gz

Format: text
Files: /usr/share/doc/mbsebbs/mbsebbs.text.gz

Format: HTML
Index: /usr/share/doc/mbsebbs/html/index.html
Files: /usr/share/doc/mbsebbs/html/*.html

  
