#!/bin/sh
# postinst script for mbsebbs
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
    # Install example bash profile if it is not already present
    if [ ! -e "/opt/mbse/.profile" ]; then
	install -m 440 /usr/share/doc/mbsebbs/examples/profile.mbse /opt/mbse/.profile
    fi

    # Install example bbbsdoor.sh script if it is not already present
    if [ ! -e "/opt/mbse/bin/bbsdoor.sh" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/bbsdoor.sh /opt/mbse/bin/bbsdoor.sh
    fi
    # Install example editor script if it is not already present
    if [ ! -e "/opt/mbse/bin/editor" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/editor /opt/mbse/bin/editor
    fi
    # Install example hatch script if it is not already present
    if [ ! -e "/opt/mbse/bin/hatch" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/hatch /opt/mbse/bin/hatch
    fi
    # Install example mbsedos script if it is not already present
    if [ ! -e "/opt/mbse/bin/mbsedos" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/mbsedos /opt/mbse/bin/mbsedos
    fi
    # Install example rundoor.sh script if it is not already present
    if [ ! -e "/opt/mbse/bin/rundoor.sh" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/rundoor.sh /opt/mbse/bin/rundoor.sh
    fi
    # Install example runvirtual.sh script if it is not already present
    if [ ! -e "/opt/mbse/bin/runvirtual.sh" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/runvirtual.sh /opt/mbse/bin/runvirtual.sh
    fi
    # Install example maint script if it is not already present
    if [ ! -e "/opt/mbse/bin/adm/maint" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/maint /opt/mbse/bin/adm/maint
    fi
    # Install example midnight script if it is not already present
    if [ ! -e "/opt/mbse/bin/adm/midnight" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/midnight /opt/mbse/bin/adm/midnight
    fi
    # Install example monthly script if it is not already present
    if [ ! -e "/opt/mbse/bin/adm/monthly" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/monthly /opt/mbse/bin/adm/monthly
    fi
    # Install example weekly script if it is not already present
    if [ ! -e "/opt/mbse/bin/adm/weekly" ]; then
	install -m 750 /usr/share/doc/mbsebbs/examples/weekly /opt/mbse/bin/adm/weekly
    fi
    
    # Install example footer.txt file if it is not already present
    if [ ! -e "/opt/mbse/etc/footer.txt" ]; then
	install -m 750 /usr/share/mbsebbs/etc/footer.txt /opt/mbse/etc/footer.txt
    fi
    # Install example header.txt file if it is not already present
    if [ ! -e "/opt/mbse/etc/header.txt" ]; then
	install -m 750 /usr/share/mbsebbs/etc/header.txt /opt/mbse/etc/header.txt
    fi
    
    # Create macros directory if not already present
    if [ ! -d "/opt/mbse/share/int/macro/" ]; then
	mkdir --mode=755 /opt/mbse/share/int/macro
    fi
    # Install english text macro files if that directory is not already present
    if [ ! -d "/opt/mbse/share/int/macro/en/" ]; then
	/bin/mkdir --mode=755 /opt/mbse/share/int/macro/en
	/bin/tar xfC /usr/share/mbsebbs/int/templates-en.tar /opt/mbse/share/int/macro/en
    fi
    
    # Create menu directory if not already present
    if [ ! -d "/opt/mbse/share/int/menu/" ]; then
	mkdir --mode=755 /opt/mbse/share/int/menu
    fi
    # Install english text menu files if that directory is not already present
    if [ ! -d "/opt/mbse/share/int/menu/en/" ]; then
	/bin/mkdir --mode=755 /opt/mbse/share/int/menu/en
	/bin/tar xfC /usr/share/mbsebbs/int/menus-en.tar /opt/mbse/share/int/menus/en
    fi
    
    # Create txtfiles directory if not already present
    if [ ! -d "/opt/mbse/share/int/txtfiles/" ]; then
	mkdir --mode=755 /opt/mbse/share/int/txtfiles
    fi
    # Install english text txtfiles files if that directory is not already present
    if [ ! -d "/opt/mbse/share/int/txtfiles/en/" ]; then
	/bin/mkdir --mode=755 /opt/mbse/share/int/txtfiles/en
	/bin/tar xfC /usr/share/mbsebbs/int/txtfiles-en.tar /opt/mbse/share/int/txtfiles/en
    fi
    
    #	Remove if present then install the stat override for setuid mbtask
    dpkg-statoverride --remove /opt/mbse/bin/mbtask >/dev/null 2>&1 || true
    dpkg-statoverride --update --add root bbs 6711 /opt/mbse/bin/mbtask
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0


