#!/bin/sh
#
# $Id$
#
# MBSE BBS Maintenance - Should be run from cron.

if [ -z "$MBSE_ROOT" ]; then
    export MBSE_ROOT=`cat /etc/passwd | grep mbse: | awk -F ':' '{ print $6}'`
fi

# Don't do maintenance if running on UPS battery power.
#
if [ -f $MBSE_ROOT/sema/upsalarm ]; then
    exit 0
fi

$MBSE_ROOT/bin/mbuser pack kill 180 50 -quiet
$MBSE_ROOT/bin/mbmsg kill pack link -quiet
$MBSE_ROOT/bin/mbfile kill pack index -quiet
$MBSE_ROOT/bin/mbaff announce filefind -quiet

cd $MBSE_ROOT/tmp
$MBSE_ROOT/bin/mball list -zip -quiet

