#!/bin/sh
#
# $Id: mbsedos,v 1.3 2004/08/11 11:11:41 mbse Exp $

if [ "`whoami`" != "mbse" ]; then
    echo "Only user 'mbse' is allowed"
    exit 1
fi

# Save initial umask and set group read/write for dos
UMASK=`umask`
umask 007

# Run DOS
if [ "$TERM" == "linux" ]; then
    dosemu.bin -f $MBSE_ROOT/etc/dosemu/dosemu.conf
else
    dosemu.bin -X -f $MBSE_ROOT/etc/dosemu/dosemu.conf
fi

# Restore umask
umask $UMASK
