#!/bin/sh
#
# FTNd Monthly - Should be run at the first day of the month at 01:30
#
# monthly 

if [ "$FTND_ROOT" = "" ]; then
   export FTND_ROOT=`cat /etc/passwd | grep ftnd: | awk -F ':' '{ print $6}'`
fi
if [ "`id -un`" != "ftnd" ] ; then
   echo "Must be run by user 'ftnd'"
   exit 1
fi

# While the system is on UPS battery power, don't start maintenance
#
while [ -f $FTND_ROOT/var/sema/upsalarm ]; do
   sleep 60
done

# Check files database and download areas.
# 
$FTND_ROOT/bin/ftnfile check index -quiet
